// Seed vocabulary for machine category → typical uses.
// Categories are common-name machinery types so they match AI analysis context.
// Freetext entry is always permitted; this list primes suggestions only.
export const MACHINE_TAXONOMY: Record<string, string[]> = {
  'Lathe': ['Metal turning', 'Shaft machining', 'Thread cutting', 'Facing', 'Boring', 'Parting off'],
  'CNC Lathe': ['CNC turning', 'Multi-axis machining', 'Automated shaft production', 'Thread cutting'],
  'Milling Machine': ['Surface milling', 'Slot cutting', 'Profile machining', 'Drilling', 'Boring'],
  'CNC Machining Centre': ['Multi-axis CNC milling', 'Automated part production', 'Drilling and tapping'],
  'Pillar Drill': ['Hole drilling', 'Counterboring', 'Reaming', 'Tapping'],
  'Radial Arm Drill': ['Hole drilling on large workpieces', 'Counterboring', 'Reaming'],
  'Surface Grinder': ['Surface grinding', 'Precision finishing', 'Deburring'],
  'Cylindrical Grinder': ['External cylindrical grinding', 'Shaft finishing'],
  'Belt Grinder': ['Deburring', 'Surface finishing', 'Weld dressing'],
  'Bench Grinder': ['Tool sharpening', 'Deburring', 'Light grinding'],
  'Power Press': ['Blanking', 'Punching', 'Deep drawing', 'Forming', 'Stamping'],
  'Hydraulic Press': ['Metal forming', 'Assembly press-fitting', 'Hydraulic forming', 'Straightening'],
  'Eccentric Press': ['Sheet metal stamping', 'Blanking', 'Piercing'],
  'Guillotine': ['Sheet metal cutting', 'Plate cropping'],
  'Bandsaw': ['Profile cutting', 'Long material cutting', 'Curved cutting'],
  'Circular Saw': ['Cross-cutting', 'Ripping timber', 'Metal bar cutting'],
  'Jig Saw': ['Curved cutting', 'Panel cutting'],
  'Plasma Cutter': ['Metal plate cutting', 'Profile cutting', 'Thick material cutting'],
  'Laser Cutter': ['Precision sheet cutting', 'Engraving', 'Tube cutting'],
  'Waterjet Cutter': ['Precision cutting', 'Stone and glass cutting', 'Composite cutting'],
  'Welding Station': ['MIG welding', 'TIG welding', 'Spot welding', 'Stick welding'],
  'Spot Welder': ['Sheet metal spot welding', 'Resistance welding'],
  'Robot / Robotic Arm': ['Welding', 'Pick and place', 'Assembly', 'Palletising', 'Painting'],
  'Conveyor': ['Material feed', 'Part transfer', 'Pallet handling', 'Product cooling', 'Assembly line feed'],
  'Roller Conveyor': ['Pallet transfer', 'Component movement', 'Assembly line feed'],
  'Belt Conveyor': ['Bulk material handling', 'Incline conveying', 'Assembly feed'],
  'Overhead Crane': ['Heavy load lifting', 'Load transfer', 'Workshop material movement'],
  'Jib Crane': ['Workstation lifting', 'Component transfer'],
  'Hoist': ['Vertical load lifting', 'Load positioning'],
  'Forklift': ['Pallet movement', 'Load stacking', 'Warehouse logistics'],
  'Injection Moulding Machine': ['Plastic part moulding', 'Rubber moulding', 'Overmoulding'],
  'Extruder': ['Plastic profile extrusion', 'Rubber extrusion', 'Film extrusion'],
  'Blow Moulding Machine': ['Hollow plastic part production', 'Bottle production'],
  'CNC Router': ['Timber routing', 'Plastic panel cutting', 'Composite machining', 'Engraving'],
  'Packaging Machine': ['Product packaging', 'Shrink wrapping', 'Sealing', 'Labelling'],
  'Palletiser': ['Pallet stacking', 'Product layer stacking', 'End-of-line automation'],
  'Air Compressor': ['Compressed air supply', 'Pneumatic tool supply', 'Process air supply'],
  'Pump': ['Fluid transfer', 'Coolant circulation', 'Chemical dosing', 'Hydraulic supply'],
  'Boiler': ['Steam generation', 'Process heating', 'Autoclave supply'],
  'Oven / Furnace': ['Heat treatment', 'Curing', 'Drying', 'Annealing', 'Powder coating cure'],
  'Shredder': ['Material shredding', 'Waste reduction', 'Document destruction'],
  'Granulator': ['Plastic regrind', 'Material size reduction'],
  'Mixer / Blender': ['Material mixing', 'Liquid blending', 'Compound mixing'],
  'Centrifuge': ['Liquid-solid separation', 'Dewatering', 'Clarification'],
  'Dust Extractor': ['Airborne dust collection', 'Fume extraction at source'],
  'Fume Extractor': ['Welding fume extraction', 'Chemical vapour extraction'],
  'Abrasive Blaster': ['Surface preparation', 'Paint removal', 'Shot peening'],
  'Thread Rolling Machine': ['External thread forming', 'Stud production'],
  'Broaching Machine': ['Internal keyway cutting', 'Profile broaching'],
  'EDM Machine': ['Electrical discharge machining', 'Die sinking', 'Wire cutting'],
  'CMM': ['Dimensional inspection', 'Part measurement', 'Quality control'],
  'Printing Machine': ['Product labelling', 'Batch coding', 'Sheet printing'],
};

export const SEED_CATEGORIES = Object.keys(MACHINE_TAXONOMY);
