import { appSchema, tableSchema } from '@nozbe/watermelondb';

// Mirrors the Azure SQL schema. server_id stores the integer PK from the server.
// is_synced tracks whether the local record has been pushed to the API.

export default appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'sites',
      columns: [
        { name: 'server_id', type: 'number', isOptional: true },
        { name: 'customer', type: 'string' },
        { name: 'project_number', type: 'string' },
        { name: 'project_description', type: 'string', isOptional: true },
        { name: 'assessor_id', type: 'number' },
        { name: 'assessor_name', type: 'string', isOptional: true },
        { name: 'date', type: 'string' },
        { name: 'created_by', type: 'number', isOptional: true },
        { name: 'is_synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'assemblies',
      columns: [
        { name: 'server_id', type: 'number', isOptional: true },
        { name: 'site_id', type: 'string' },
        { name: 'assembly_name', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'is_synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'machines',
      columns: [
        { name: 'server_id', type: 'number', isOptional: true },
        { name: 'assembly_id', type: 'string' },
        { name: 'machine_name_reference', type: 'string' },
        { name: 'serial_number', type: 'string', isOptional: true },
        { name: 'manufacturer', type: 'string', isOptional: true },
        { name: 'model', type: 'string', isOptional: true },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'picture_url', type: 'string', isOptional: true },
        { name: 'nameplate_photo_url', type: 'string', isOptional: true },
        { name: 'is_synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'question_sets',
      columns: [
        { name: 'server_id', type: 'number', isOptional: true },
        { name: 'set_name', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'is_base', type: 'boolean' },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'questions',
      columns: [
        { name: 'server_id', type: 'number', isOptional: true },
        { name: 'question_set_id', type: 'string' },
        { name: 'question_reference', type: 'string' },
        { name: 'question_number', type: 'string' },
        { name: 'question_text', type: 'string' },
        { name: 'regulation_number', type: 'number' },
        { name: 'q_index', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'checklist_instances',
      columns: [
        { name: 'server_id', type: 'number', isOptional: true },
        { name: 'machine_id', type: 'string' },
        { name: 'assessor_id', type: 'number' },
        { name: 'assessor_name', type: 'string', isOptional: true },
        { name: 'date', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'is_synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'checklist_responses',
      columns: [
        { name: 'server_id', type: 'number', isOptional: true },
        { name: 'checklist_id', type: 'string' },
        { name: 'question_id', type: 'string' },
        { name: 'answer', type: 'string' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'photo_url', type: 'string', isOptional: true },
        { name: 'is_synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'risk_evaluations',
      columns: [
        { name: 'server_id', type: 'number', isOptional: true },
        { name: 'machine_id', type: 'string' },
        { name: 'checklist_id', type: 'string', isOptional: true },
        { name: 'hazard_description', type: 'string' },
        { name: 'hazard_category', type: 'string' },
        { name: 'photo_url', type: 'string', isOptional: true },
        { name: 'pre_control_severity', type: 'string' },
        { name: 'pre_control_probability', type: 'string' },
        { name: 'pre_control_score', type: 'number' },
        { name: 'pre_control_rating', type: 'string' },
        { name: 'control_description', type: 'string', isOptional: true },
        { name: 'post_control_severity', type: 'string' },
        { name: 'post_control_probability', type: 'string' },
        { name: 'post_control_score', type: 'number' },
        { name: 'post_control_rating', type: 'string' },
        { name: 'created_by', type: 'number', isOptional: true },
        { name: 'is_synced', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
});
